# --------------
# -- Settings --
# --------------

# Ignore this. This is only if you're hosting this in a sub-folder.
# If you're using GitHub pages, they automatically override this with the right value.
baseurl: ""

# If you're using GitHub pages without a custom domain, this is "https://[github username].github.io"
# If you're using GitHub pages with a custom domain, this is "http://[your domain]" (or https if you're using SSL)
url: "https://adrianaixba.github.io/elhackaton"

# The ability to use custom themes.
style:
  theme: "jekyll-theme-cayman"

# This will help you track who's visiting your website.
tracking:
  google_analytics: "UA-43729070-14"

# Let people connect & engage with you through social media.
social:
  twitter_handle: "MLHacks"

# This is Search Engine Optimization. It'll help your website look better on search.
seo:
  title:       "El Hackatón | 21/22 October 2017"
  description: "Welcome to El Hackatón!"
  image:       "https://prime.mlh.io/img/logos/mlh-prime-color.svg"

# Event information.
event:
  name:        "El Hackatón"
  description: "Welcome to El Hackatón!"
  date:        "21 & 22 October 2017"
  location:    "Austin, TX, United States"

  trust_badge:
    year:   "2017"  # season year
    region: "eu"    # "na" or "eu"
    color:  "yellow" # "white", "black", "gray", "red", "blue" or "yellow"

  hero:
    links:
      - text: "Apply"
        my_mlh:
          client_id:    "0e2f9fc2921d3ad3e12ae900af630d09382e1b3dc1b5b50de2b01b70ad64dbee"
          redirect_uri: "https://mlh.github.io/mlh-hackathon-boilerplate/success.html"
      - text: "Sponsor"
        href: "mailto:sponsorship@website.com"

  about:
    description: >
      El Hackatón is a hackathon hosted at The University of Texas at Austin.
      The purpose of our event is to break cultural stereotypes as well as empower 
      one of the most important demographics in our country, and sadly one of the least 
      recognized in the Tech industry. Do not misunderstand the concept; we are happy to include 
      people of all backgrounds in the event but have the mission to bring a hackathon opportunity 
      to students who might not usually attend these events, by creating a familiar environment.
      
  # Info Sections
  info:
    sections:
      - image: "images/image1.png"
        title: "BUILD."
        description: >
          Create something new, or something you've always wanted to build with the help of teammates 
          or technical volunteers that can answer all your hacking questions!
      - image: "images/image2.png"
        title: "LEARN."
        description: >
          Experience is the main driver for a great educational experience! Our tech talks and workshops will
          guarantee this knowledgable experience.
      - image: "images/image3.png"
        title: "SHARE."
        description: >
          Meet new friends, and share your knowledge and ideas in a fun environment!

  # Frequently asked questions.
  faq:
    - question: "Who are we?"
      answer: >
        Our team, Los Hackers, is a focused diverse group of 13 University Of Texas Computer 
        Science students. Our intention is to create a hackaton, El Hackatón, to give people in our
        community the opportunity to have unique empowering experience. Our goal is to provide
        Hispanic members of our community, tools to gain experience working in technology. We
        want to do this by giving them a safe space, so they are able to express themselves,
        collaborate, and learn through innovative thinking. We want to provide participants with
        tech talks, skill building workshops, and the tech instruments to supply the innovative ideas
        of novices and experienced hackers.
    - question: "How much does it cost?"
      answer: >
        Nothing. Attending a hackathon is free.
    - question: "Out of the area hackers?"
      answer: >
        If you don't live in the area, make sure to mention it while filling out your application. We have sponsors who will
        be willing to sponsor your experience, so you don't have to spend a dime! As we review and accept the candidate's applications, we will follow up with an email
        on your transportation updates.
    - question: "Do I need to be a student to attend?"
      answer: >
        Yes. Only students who are currently enrolled at a college/university or
        have graduated within the past 12 months are eligible to attend.
    - question: "Where is the event?"
      answer: >
        The event is being hosted at The University of Texas at Austin.
    - question: "What is Major League Hacking?"
      answer: >
        Major League Hacking is [the official student hackathon league](https://mlh.io) in North America & Europe.
        We work with over 200 Member Events and empower over 70,000 students every year.
    - question: "How do teams work"
      answer: >
        You will be able to form a team with the limit of 5 people, but you may also work alone. If you don't have a team yet,
        don't worry! Before coding begins, you will be able to meet new people who are also looking for teammates.
    - question: "Is there a code of conduct?"
      answer: >
        Yes there is. We enforce it very strongly. You can [find it here](https://static.mlh.io/docs/mlh-code-of-conduct.pdf).
    - question: "Who could we contact for more information?"
      answer: >
        You can contact el.hackaton@gmail.com for any questions you may have.

  # This is the message you'll receive once you've registered.
  register:
    message: >
      You'll receive more information closer to the hackathon.

# ----------------------------------------------------
# -- Ignore this unless you know what you're doing. --
# ----------------------------------------------------

markdown: kramdown
exclude:
 - node_modules
 - gulpfile.js
 - Gemfile
 - Gemfile.lock
 - package.json
 - README.md
 - CNAME

theme: jekyll-theme-cayman
